name: Publish Frontend Container Image
on:
  release:
    types: [push, pull_request]
jobs:
  push_to_registry:
    name: Push image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v4
        with:
          github-token: ${{ github.token }}
          repository: dazzla76/first-microservice/frontend
          tag_with_ref: true
          dockerfile: ./frontend/Dockerfile
